Repository MinhaCena/minha-cena-site, pull requests merged in 2023-04, with the labels that each got.

#25 feat: make the site responsive
  .gitignore
  public/icons/close.svg
  public/icons/hamburguer.svg
  public/img/logo-hero.png
  public/lotties/comingsoon.json
  src/app/layout.tsx
  src/components/ButtonLink/index.tsx
  src/components/ButtonLink/styles.module.scss
  src/components/InputField/index.tsx
  src/components/InputField/styles.module.scss
  src/components/Layout/Footer/index.tsx
  src/components/Layout/Footer/styles.module.scss
  src/components/Layout/Header/index.tsx
  src/components/Layout/Header/styles.module.scss
  src/components/Sections/SectionAbout/index.tsx
  src/components/Sections/SectionAbout/styles.module.scss
  src/components/Sections/SectionContact/index.tsx
  src/components/Sections/SectionContact/styles.module.scss
  src/components/Sections/SectionHero/index.tsx
  src/components/Sections/SectionHero/styles.module.scss
  src/components/Sections/SectionMotivation/index.tsx
  src/components/Sections/SectionMotivation/styles.module.scss
  src/components/Sections/SectionPartners/styles.module.scss
  src/components/Sections/SectionRecommend/index.tsx
  src/components/Sections/SectionRecommend/styles.module.scss
  src/components/Sections/SectionSubscribe/styles.module.scss
  src/components/UI/LottieAnimation/index.tsx
  src/components/UI/LottieAnimation/styles.module.scss
  src/styles/globals.scss
  src/styles/theme/breakpoints.scss
Labels: responsiveness

#26 docs: add instructions to README
  README.md
Labels: docs

#28 Add Animations
  .eslintrc.json
  package-lock.json
  src/components/Sections/SectionAbout/index.tsx
  src/components/Sections/SectionAbout/styles.module.scss
  src/components/Sections/SectionHero/index.tsx
  src/components/Sections/SectionHero/styles.module.scss
Labels: feat

#31 refactor: changes directory structure and Next.js layout page
  src/app/layout.tsx
  src/app/page.tsx
  src/app/terms/page.tsx
  src/app/terms/styles.module.scss
  src/components/Layout/Footer/index.tsx
  src/components/Layout/Footer/styles.module.scss
Labels: refactor
